pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.19' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps: 
- task: GoTool@0
  inputs:
    version: '1.21'

- task: Go@0
  inputs:
    command: 'get'
    arguments: '-t LogisticsRoutes/internal'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  inputs:
    command: 'test'
    arguments: './...'
    workingDirectory: '$(System.DefaultWorkingDirectory)'