name: Execute Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    name: 'Go test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies 
        run: go mod download
      - name: Execute tests
        run: 'go test -v ./...'