name: Execute Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.11','1.18', '1.19']

    name: 'Go ${{matrix.go-version}} test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go-version}}

      - name: Install dependencies 
        run: |
          sed -i 's/1.21/${{matrix.go-version}}/g' go.mod
          go mod download
          go mod tidy
      - name: Execute tests
        run: 'go test -v ./...'